### ISSUE TITLE
Missing: using System.Reflection; GetMethod() build error : AppCenterInternal.cs Line 174

### ISSUE THREAD

**Issue by paseb** [Microsoft/AppCenter-SDK-Unity#152]
Looks like you're missing the reference to using Reflection in AppCenterInternal.cs:
- using System.Reflection;

With other build issues in the past I've had to use TypeInfo to get the declared methods and iterate them per this thread:
- https://stackoverflow.com/questions/45229305/type-does-not-contain-a-definition-for-getmethod

**Comment by patniko** [comment]
Will ship an update shortly @paseb. 👍

**Comment by max-mironov** [comment]
Hey @paseb, thanks for pointing out! 
You are speaking about adding `using System.Reflection;` [in this file](https://github.com/Microsoft/AppCenter-SDK-Unity/blob/develop/Assets/AppCenter/Plugins/AppCenterSDK/Core/UWP/AppCenterInternal.cs#L8), correct? 
We can add this, however could you please also let us know how to reproduce this build error on our side so that we will be sure that we are not missing anything in future? 
Also what [scripting backend](https://docs.unity3d.com/Manual/windowsstore-scriptingbackends.html) you are using while building?

**Comment by paseb** [comment]
I'm using the close to latest version of unity 2018.2.10f1 and using .Net as the backend.  This is a requirement for some of our internal libraries.  This should be easy to repo as all you have to do is:

- Create a new project
- Target WSA in the build settings
- Set .Net as the scripting backend
- Import the Analytics unity package
- Try to build out a solution

This should give you the following error:
`Assets\AppCenter\Plugins\AppCenterSDK\Core\UWP\AppCenterInternal.cs(174,42): error CS1061: 'Type' does not contain a definition for 'GetMethod' and no extension method 'GetMethod' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)`

In the past as I mentioned, there's been issues in changes to UWP and no longer having access to GetMethod as it's part of .Net 4 and wasn't available in the earlier .Net Unity was using at the time.  However that's resolved in the current versions of Unity.

thanks,
-pat

**Comment by annakocheshkova** [comment]
@paseb thanks for pointing that out!
We've made this fix in [the PR](https://github.com/Microsoft/AppCenter-SDK-Unity/pull/154). The release will be made soon.
