### ISSUE TITLE
AppCenterDemoApp test instructions.

### ISSUE THREAD

**Issue by junpark12** [Microsoft/AppCenter-SDK-Unity#247]
Hi i downloaded demo app and replace app's secret it with my own.
But after build & run, i cannot check "app center enabled" .
Do we have any instructions to follow to run it properly?
Thanks
![image](https://user-images.githubusercontent.com/20918194/53553745-b0877c80-3b81-11e9-86de-714a3265448c.png)

**Comment by MatkovIvan** [comment]
Hi @junpark12,

Thanks for getting in touch!
Please look at the logs, are there any error messages here?

Thanks,
Ivan

**Comment by junpark12** [comment]
Hi @MatkovIvan 
When i run the app and clicked some buttons on crashes tab. 

![image](https://user-images.githubusercontent.com/20918194/53707596-f3dc3680-3e72-11e9-9d01-373de0b71e6b.png)

But when i see the source code in visual studio,  i found out that the following method is empty.
Microsoft.AppCenter.Unity.Crashes.Internal.CrashesInternal
![image](https://user-images.githubusercontent.com/20918194/53707659-3998ff00-3e73-11e9-98c1-d7234f5cc029.png)

I want to see something in appcenter's diagnostics when my app went go wrong(handled or unhandled exceptions). How can i accomplish this?
Thanks.

**Comment by annakocheshkova** [comment]
Hey @junpark12, what is the platform you are trying to test on?
This exception you are seeing should crash your app and send this crash info to App Center on next restart.
And the code you are looking at seems to be from the `Blank/CrashesInternal` file which is a stub for UnityEditor app preview and this is totally fine. If you look under `Android/CrashesInternal`, for example, there is implementation.

And as for App Center not being enabled, this usually happens when app secret is incorrect, what are your AppCenter settings in Unity Editor?

**Comment by junpark12** [comment]
Hi @annakocheshkova 
I built the app using default setting which is standalone windows app. 
i put app's secret in uwp property.
![image](https://user-images.githubusercontent.com/20918194/53773585-57776a00-3f2e-11e9-8b37-d31769ecef12.png)

I wanted to run the application as windows app and wanted to see diagnostics messages in app center portal.

**Comment by annakocheshkova** [comment]
@junpark12 unfortunately, crashes module is not supported for UWP yet - only Android/iOS.

**Comment by annakocheshkova** [comment]
@junpark12 do you have any other issues or questions? We'll be glad to help.

**Comment by junpark12** [comment]
oh that's it thanks.
