### ISSUE TITLE
Why "unhandled exceptions" on android tracked in coroutine?

### ISSUE THREAD

**Issue by cNoNim** [Microsoft/AppCenter-SDK-Unity#304]
Can someone explain history of that code?

https://github.com/microsoft/appcenter-sdk-unity/blob/0da3d1287a86b86cf04a8d2aa462413f62b202a0/Assets/AppCenter/Plugins/AppCenterSDK/Crashes/Shared/Crashes.cs#L88

I was seeing in git blame:

at some point, coroutine was creating in subscription to unhandled exceptions, then in this commit https://github.com/microsoft/appcenter-sdk-unity/pull/187 coroutine creation was moved to exception handling

And now we produce new coroutines for each exception... any reasons for that?

And main question is coroutine creation and execution does not works in multithreaded application, which purpose of using queue with locking?
Why exception handling tracked in coroutine and only for android?

This behaviour complicates solutions like https://github.com/microsoft/appcenter-sdk-unity/issues/242.

In teory we want set some properties in some place before exception throwing and clear them after. But async exception tracking make that painfull.

**Comment by Jamminroot** [comment]
Hey, @cNoNim, thanks for getting in touch.
Please, give us some time to investigate it.

**Comment by Jamminroot** [comment]
Ok, I've got an update on the problem.
It appears, that at that time we had to run the code in the main thread, since other approaches ended up with error messages of exceptions thrown not being quite clear and understandable.

**Comment by cNoNim** [comment]
I understand reason for use coroutine, but its not android only problem, and now solution broken, cause StartCoroutine, FindObjectOfType and new GameObject() can (or should) be used from main thread only.

**Comment by annakocheshkova** [comment]
@cNoNim as mentioned, calling `TrackException` without async block / not on main thread causes errors. That's because creating JNI objects should be done either on main thread or using `AndroidJNI.AttachCurrentThread() / DetachCurrentThread()` (see [documentation](https://docs.unity3d.com/ScriptReference/AndroidJavaObject.html)) which has already been tried and didn't work in our case. 
I just verified this behaviour and got 
```
 E/zygote: JNI ERROR (app bug): accessed stale Local 0x9  (index 0 in a table of size 0)
 A/zygote: java_vm_ext.cc:534] JNI DETECTED ERROR IN APPLICATION: use of deleted local reference 0x9
```
However, if you want, you can use `TrackException` the way it is convenient for you, by turning off `Crashes.ReportUnhandledExceptions(false);` .
