### ISSUE TITLE
[QUESTION] Start AppCenter manually

### ISSUE THREAD

**Issue by liszto** [Microsoft/AppCenter-SDK-Unity#324]
Hello again (sorry for  those tickets),
In our projects, we have what we called profiles that we use to build our application with different skins etc...

Each profile can have a different bundle ID and so a different HockeyApp ID. So in your case different secret app id.
So we can't have the component directly on an object in our scene so the AppCenterBehavior doesn't exist before build and soo the AppCenterSettings that could be create or already present in the "AppCenter" folder doesn't have any information when we build. 
We try to instantiate it at runtime and so we fill it with information retrieve from our profile file.

If we do this it seems to be mandatory to add the AppCenterBehaviorAdvanced component with 
`StartAndroidNativeSDKFromAppCenterBehavior` set to `true` otherwise it doesn't work am I correct ?
Because when the AppCenter can't start from the native side on Start, it won't succeed to start the AppCenter when the component is added with an `AddComponent` by code.

**Comment by annakocheshkova** [comment]
Hey again @liszto! No problems, you make very valuable contributions to our SDK! We are constantly trying to make it better so appreciate that.
 
About the issue: indeed, you're right about this one. 
But if you decide to start manually, keep in mind several things: 
For UWP, in order to be able to subscribe to Push/Distribute events, you need to move the start of the SDK to `Start` (not `Awake`). It might cause Analytics not work in `Awake`.
Also pay attention to the script initialization order if you want to implement a crash dialog.

**Comment by liszto** [comment]
Yep that's right for UWP but we currently don't target this platform so it's ok.
And it's a good to remember me the initialization order concerning the crash dialog if we wanna implement it one day :)

**Comment by annakocheshkova** [comment]
Great! Feel free to re-open this one if you encounter issues with manual start.

**Comment by liszto** [comment]
Concerning the AppCenterBehaviorAdvanced & AppCenterBehavior combo maybe it could be could to mention it in the documentation cause currently I didn't find this anywhere or maybe I missed it ;)

**Comment by annakocheshkova** [comment]
It's [here](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/unity#delay-the-start-of-app-center)

**Comment by annakocheshkova** [comment]
Not the first thing that you see but that's a very rare use case
