### ISSUE TITLE
Conflict between Azure Spatial Anchors SDK and App Center SDK.

### ISSUE THREAD

**Issue by mrwellmann** [Microsoft/AppCenter-SDK-Unity#496]
### **Description**
There is a conflict between Azure Spatial Anchors SDK and App Center SDK because ASA uses the App Center SDK.
I posted this also on https://github.com/Azure/azure-spatial-anchors-samples/issues/272#issue-938802783

#### Excerpt from gradleTemplate.properties
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation('com.squareup.okhttp3:okhttp:[3.11.0]')
    implementation('com.microsoft.appcenter:appcenter-analytics:[1.10.0]'){
    }
```

#### Excerpt from the Editor log:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.microsoft.appcenter.AbstractAppCenterService found in modules appcenter-1.10.0-runtime.jar (com.microsoft.appcenter:appcenter:1.10.0) and appcenter-release-runtime.jar (:appcenter-release:)
  Duplicate class com.microsoft.appcenter.AbstractAppCenterService$1 found in modules appcenter-1.10.0-runtime.jar (com.microsoft.appcenter:appcenter:1.10.0) and appcenter-release-runtime.jar (:appcenter-release:)
```

The solution mentioned here https://github.com/microsoft/appcenter-sdk-unity/issues/369#issuecomment-558834269 is not working for me.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Use ASA Unity sample
2. Use MixedRealityFeatureTool-1.0.2104.4-Beta (Probably not needed)
2. Add AppCenterEditorExtensions-v3.0.0.unitypackage
3. Add App Centrer Analytics
4. Open AzureSpatialAnchorsBasicDemo and add App Center Behaviour
5. Set Android Build Target
6. Build
7. Open Editor Log (unity console has issues displaying the error)

Feel free to use the sample git@github.com:firedrill-gmbh/ASA-AppCenter-TestCase.git

**Comment by DmitriyKirakosyan** [comment]
Hi @mrwellmann 

Thank you for reaching out to us and thank you for you sample project!

The problem is, as you mentioned, that ASA SDK uses App Center Analytics and it conflicts with the App Center SDK that you integrate in your App. I believe this is not an AppCenter SDK issue.
Regarding [this solution](https://github.com/microsoft/appcenter-sdk-unity/issues/369#issuecomment-558834269) that you pointed out. Have you tried to modify the launcherTemplate.gradle as well? You can find some info about the file [here](https://docs.unity3d.com/Manual/android-gradle-overview.html).
Also, have you tried to use [Unity jar resolver](https://github.com/googlesamples/unity-jar-resolver)?

I couldn't launch your app due to some unity versions incompatibility. 
I will try to fix the versioning issue and run your sample, and let you know if I find any solution/workaround.

**Comment by mrwellmann** [comment]
Hi @DmitriyKirakosyan,

thanks for the quick feedback. I was writing here as the last time this issue popped up it was here where the fix was found.
___
>Regarding [this solution](https://github.com/microsoft/appcenter-sdk-unity/issues/369#issuecomment-558834269) that you pointed out. Have you tried to modify the launcherTemplate.gradle as well?

No I did not. I just quickly checked. The issue stay the same.
` Could not find method natives() for arguments [com.microsoft.azure.spatialanchors:spatialanchors_ndk:[2.9.0]] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

`com.microsoft.azure.spatialanchors:spatialanchors_ndk` is actually not any more part of the modifications the ASA SDK does.

The modifications from ASA SDK on the mainTemplate.gradle look like this now
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation('com.squareup.okhttp3:okhttp:[3.11.0]')
    implementation('com.microsoft.appcenter:appcenter-analytics:[1.10.0]')
**DEPS**}
```
___
> Also, have you tried to use Unity jar resolver?

We use it in our the Unity jar resolver in our application, but I'm not an expert on the topic.
You mean if I tried to resolve Android Dependencies, right?
![image](https://user-images.githubusercontent.com/247111/125065994-c9d65700-e0b2-11eb-8d76-e4b4f6769eba.png)
I also added it to the sample project.
___

**The solution should be to tell ASA SDK to use appcenter-release-runtime.jar instead of appcenter-1.10.0-runtime.jar and not include the appcenter-1.10.0-runtime.jar right? I just don't know how to do this.**

**Comment by DmitriyKirakosyan** [comment]
hi @mrwellmann 

Thank you for the details.
Try to remove the line `implementation('com.microsoft.appcenter:appcenter-analytics:[1.10.0]')` from your `mainTemplate.gradle`, so it would look like this:
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation('com.squareup.okhttp3:okhttp:[3.11.0]')
**DEPS**}
```

I'm not sure if ASA will function properly without this dep. But if [this solution](https://github.com/microsoft/appcenter-sdk-unity/issues/369#issuecomment-558834269) worked, then it should.

Additionally you can try to add these lines to the `mainTemplate.gradle`:
```
implementation(name: 'spatialanchors_ndk', ext:'aar') {
   exclude group: 'com.microsoft.appcenter'
}
```

I reproduced your issue and these modifications made the build finish successfully for me. However, it crashes with some graphics issues. Perhaps, because I ran it on emulator.

Please let me know if that worked for you.

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.

**Comment by Silloty1** [comment]
Hello
Sorry @mrwellmann is currently in holidays so I am handling the ticket for now. I tried to apply the fixes mentionned in [that issue ](https://github.com/microsoft/appcenter-sdk-unity/issues/369#issuecomment-558834269) and also remove the line `implementation('com.microsoft.appcenter:appcenter-analytics:[1.10.0]')`, but it still doesn't work. The error is the following : ` Could not find method natives() for arguments [com.microsoft.azure.spatialanchors:spatialanchors_ndk:[2.9.0]] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler`

**Comment by DmitriyKirakosyan** [comment]
Hi @Silloty1 and @mrwellmann 

I prepared a PR to your demo app with the fix : https://github.com/firedrill-gmbh/ASA-AppCenter-TestCase/pull/1.
Please check if it works for you.

**Comment by mrwellmann** [comment]
@DmitriyKirakosyan thanks a lot!
With your fix I was able to build a working .apk but I still got a failed build which was very stage. After some digging and trial and error the fix seems to add `//implementation('com.microsoft.appcenter:appcenter-analytics:[1.10.0]')` My guess is something in the ASA SDK is searching for it but does not care that its commented-out.

I will publish this solution also into the ASA GitHub repo.

**Comment by DmitriyKirakosyan** [comment]
I'm glad the issue is resolved for you!
